name: inshort_clone
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl:
  dio: ^5.2.0+1
  cupertino_icons: ^1.0.5
  flutter_feather_icons: ^2.0.0+1
  auto_route: ^7.4.0
  webview_flutter: ^4.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive:
  hive_flutter:
  path_provider: ^2.0.15
  esys_flutter_share_plus: ^2.2.0
  provider:
  photo_view: ^0.14.0
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.3
  meta: ^1.9.1
  permission_handler:
    ^10.3.0

    # For Improving Code Quality
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^7.1.1
  hive_generator:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/kn.json
    - assets/lang/hi.json
    - assets/lang/mr.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
